-- View: v_split_metrics
-- Aggregates per-split LLM signals (paid_by_match, confidence) and human
-- override flags for the analytics dashboard. See docs/SCHEMA.md for the
-- semantics of paid_by_match.
--
-- This view is hand-written, not generated by drizzle-kit, because Drizzle's
-- relational query API does not model views. Queries against this view use
-- raw SQL via db.execute(sql`...`).

CREATE VIEW v_split_metrics AS
SELECT
  s.id AS split_id,
  s.receipt_id,
  r.household_id,
  r.date AS receipt_date,
  s.paid_by_match,
  s.is_settled,
  s.created_at AS split_created_at,
  -- Most recent task-source confidence on this split (null if LLM never ran)
  (
    SELECT c.confidence
    FROM changes c
    JOIN split_history sh ON sh.change_id = c.id
    WHERE sh.split_id = s.id
      AND c.source LIKE 'task:%'
    ORDER BY c.created_at DESC
    LIMIT 1
  ) AS llm_confidence,
  -- Did a human edit paidByUserId at any point? (irrespective of LLM outcome)
  EXISTS (
    SELECT 1
    FROM changes c
    JOIN split_history sh ON sh.change_id = c.id
    WHERE sh.split_id = s.id
      AND sh.field = 'paidByUserId'
      AND c.source LIKE 'user:%'
  ) AS paid_by_overridden_by_human
FROM splits s
LEFT JOIN receipts r ON r.id = s.receipt_id;
--> statement-breakpoint
