# Database for Local Development
services:
  postgres:
    image: postgres:17-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tallysplit
      POSTGRES_PASSWORD: tallysplit
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
