import { getGpt4oConfig } from './get-gpt4o-config.js'

/**
 * Normalize receipt data using GPT-4o-mini (text-only, no vision).
 * Reconciles inconsistent OCR date/time fields and generates a receipt title.
 *
 * @param {Object} params
 * @param {Object} params.transactionDate - OCR TransactionDate field ({ content, valueDate })
 * @param {Object} params.transactionTime - OCR TransactionTime field ({ content, valueTime })
 * @param {string} params.merchantName - Merchant name from receipt
 * @param {Object[]} params.lineItems - Line items from OCR ({ description, quantity, totalPrice })
 * @param {string} params.originalFilename - Original upload filename
 * @returns {Promise<Object>} { date, time, title, filenameIsHumanNamed }
 */
export async function normalizeReceipt ({ transactionDate, transactionTime, merchantName, lineItems, originalFilename }) {
  const { endpoint, key } = getGpt4oConfig()

  const systemPrompt = `You are a receipt data normalizer. You will receive raw OCR data from a receipt and must produce clean, normalized output.

The receipts are generally in German (from Germany), but your output must always be in English.

## Task 1: Normalize date and time

You receive TransactionDate and TransactionTime fields from Azure Document Intelligence OCR.
Each field has a "content" (raw text from the receipt) and a parsed value ("valueDate" or "valueTime").

Known issues:
- valueDate is correct ~80% of the time, but sometimes has the wrong year when "content" contains a full ISO timestamp
- valueTime is reliable when present
- Time "content" may have "Uhr" suffix or be truncated to HH:MM
- Some receipts have no time at all

Rules:
- Compare "content" against the parsed value. If they conflict, prefer "content" as the ground truth and reason about the correct date
- Return date as ISO date string (YYYY-MM-DD)
- Return time as ISO time string (HH:MM:SS) or null if no time is available
- If the date cannot be determined at all, return null

## Task 2: Generate receipt title

Generate a concise title in English in the format: "<merchant name> - <category>"
where <category> summarizes what was purchased (e.g., "Groceries", "Dinner", "Office Supplies").

For the merchant name, use the everyday colloquial name — NOT the legal entity name.
Examples:
- "MH Müller Handels GmbH" → "Müller"
- "Rewe Markt GmbH" → "Rewe"
- "dm-drogerie markt GmbH + Co. KG" → "dm"

Special case: Some German supermarkets (e.g. Edeka) are franchises where individual store owners' names appear on receipts (e.g. "Michael Mustermann e.K." as merchant, "Edeka Mustermann" elsewhere). If a well-known chain name like "Edeka" appears anywhere on the receipt, use that as the merchant — ignore the franchisee's personal name.

If there are fewer than 3 items, you may combine them into a key phrase instead of a category (e.g., "Coffee & Cake").

Note: Line item descriptions will be in German. Translate the category/phrase to English.

## Task 3: Detect human-named filenames

The original filename is provided. Determine if it was named by a human or auto-generated by a camera/scanner.

Auto-generated examples: "Screenshot 2026-03-29 at 16.25.22.png", "IMG_20260123_164708.jpg", "Scanned_20260123-1647-08.jpg", "PXL_20251107_174500.jpg"
Human-named examples: "2026-01-03 Rewe (28.69).jpg", "Dinner with friends.png", "Office supplies receipt.jpg"

Return JSON:
{
  "date": "YYYY-MM-DD" or null,
  "time": "HH:MM:SS" or null,
  "title": "<merchant> - <category>",
  "filenameIsHumanNamed": true/false
}`

  const userMessage = JSON.stringify({
    transactionDate: transactionDate || null,
    transactionTime: transactionTime || null,
    merchantName: merchantName || 'Unknown',
    lineItems: lineItems || [],
    originalFilename,
  }, null, 2)

  let response
  try {
    response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'api-key': key,
      },
      body: JSON.stringify({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userMessage },
        ],
        temperature: 0,
        response_format: { type: 'json_object' },
      }),
    })
  }
  catch (err) {
    console.error('[gpt4o fetch failed]', {
      endpoint,
      cause: err.cause?.message,
      code: err.cause?.code,
      hostname: err.cause?.hostname,
    })
    throw err
  }

  const responseText = await response.text()

  if (!response.ok) {
    throw new Error(`GPT-4o normalize failed (${response.status}): ${responseText}`)
  }

  const result = JSON.parse(responseText)
  const content = result.choices?.[0]?.message?.content

  if (!content) {
    throw new Error('GPT-4o normalize returned empty content')
  }

  return {
    ...JSON.parse(content),
    model: result.model,
  }
}
